# 1.2. Векторы. Основные понятия

In [2]:
import numpy as np

In [34]:
apartment = np.array([59.50, 31.40, 19, 22, 60550, 2])

In [35]:
print("ndim:", apartment.ndim) 

ndim: 1


In [47]:
print("shape:", apartment.shape)

shape: (5,)


In [37]:
share_living_space = apartment[1]/apartment[0]

In [38]:
share_living_space

0.5277310924369748

In [39]:
apartment = np.delete(apartment, [0,1])

In [40]:
apartment

array([1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00])

In [41]:
apartment = np.append(apartment, share_living_space)

In [42]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [43]:
apartment.round(2)

array([1.900e+01, 2.200e+01, 6.055e+04, 2.000e+00, 5.300e-01])

In [44]:
apartment = apartment.astype(float)

In [45]:
apartment

array([1.90000000e+01, 2.20000000e+01, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [46]:
print("ndim:", apartment.ndim) 

ndim: 1


# 1.3. Базовые операции над векторами

In [48]:
a = np.array([10,8,5,1])
b = np.array([5,15,9,7])

In [49]:
a+b

array([15, 23, 14,  8])

In [50]:
a-b

array([ 5, -7, -4, -6])

In [51]:
c = np.array([120,45,68])

In [52]:
omega = 0.2

In [53]:
comission = omega*c

In [54]:
comission

array([24. ,  9. , 13.6])

## Задание 1.3.1

In [151]:
x = np.array([1,2,3**(1/2)])

In [152]:
x

array([1.        , 2.        , 1.73205081])

In [153]:
y = np.array([-1,-2])

In [154]:
y

array([-1, -2])

In [155]:
x+y

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

## 1.3.2. Task

In [65]:
x2 = np.array([5,2])

In [66]:
y2 = np.array([-5,-11])

In [67]:
x2+y2

array([ 0, -9])

In [68]:
x2-y2

array([10, 13])

## 1.3.3. Task

In [86]:
husband = np.array([120,150,90])

In [80]:
wife = np.array([130,130,130])

In [81]:
wife_mom = np.array([2,3,2.5]) #Euro 

In [82]:
exchange_rate = 72

In [88]:
wife_mom_uah = wife_mom*exchange_rate
wife_mom_uah

array([144., 216., 180.])

In [89]:
husband+wife+wife_mom_uah

array([394., 496., 400.])

# 1.4. Linear Combination of Vectors

У агента Алексея есть канал в Telegram, где он формирует очередь на показы трёх особенно привлекательных квартир. Premium показ стоит  500 рублей, VIP показ — 100 рублей, обычный показ — бесплатно. За неделю по каждой квартире было 2, 4 и 5 Premium показов, 8, 10 и 2 VIP показа и 0, 12 и 7 обычных показов соответственно. Сколько заработал на показах по каждой квартире Алексей?

In [94]:
p = np.array([2,4,5])

In [95]:
v = np.array([8,10,2])

In [96]:
f = np.array([0,12,7])

In [99]:
total_earnings = 500*p + 100*v + 0*f

In [100]:
total_earnings

array([1800, 3000, 2700])

## 1.4.1 

In [103]:
x = np.array([4,5])
y = np.array([2,1])
u = np.array([1,0])

In [104]:
2*x-3*y+5*u

array([7, 7])

## 1.4.2

In [108]:
produced = np.array([3,4,5,9])
sold = np.array([1,5,3,6])
cost = 200
price = 400
r = sold * price - produced*cost
r

array([-200, 1200,  200,  600])

# 1.5 Scalar vector multiplication

## 1.5.2

In [109]:
x = np.array([4,5,-1])
y = np.array([2,0,1])

In [110]:
np.dot(x,y)

7

## 1.5.4

In [111]:
x = np.array([4,6,1])
np.dot(x,x)**(1/2)

7.280109889280518

# 1.7 Vectors. Practice in Python

## Task 1

## 1.7.1

In [113]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [114]:
Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

In [119]:
A = Hut_Paradise_DF.values
print('Matrix numpy:\n', A)

Matrix numpy:
 [[ 65  50   3   5   8  37]
 [ 70  52   2  12   4  40]
 [120  80   1  10   5  65]
 [ 35  33   1   3  10  20]
 [ 40  33   1   6  20  16]
 [ 50  44   2  13  12  35]
 [100  80   4   8   5  60]
 [ 90  65   3  21   1  50]
 [ 85  65   2   5  10  40]]


In [122]:
App_2 = A[4]
print('fifth apartment vector:\n', App_2)

fifth apartment vector:
 [40 33  1  6 20 16]


## 1.7.2

In [123]:
print('floors vector:\n', A[:,3])

floors vector:
 [ 5 12 10  3  6 13  8 21  5]


## 1.7.3

In [124]:
print('apartment 3 floor:\n', A[2,3])

apartment 3 floor:
 10


## 1.7.4

In [126]:
print('number of apartments:\n',len(A))

number of apartments:
 9


## 1.7.5

In [128]:
non_live = A[:,1]-A[:,5]
print('non living area:\n',non_live)

non living area:
 [13 12 15 13 17  9 20 15 25]


## 1.7.6

In [130]:
print('Rent in UAH:\n', A[:,0]*0.4)

Rent in UAH:
 [26. 28. 48. 14. 16. 20. 40. 36. 34.]


## 1.7.7

In [134]:
looking_time = np.array([10,20,30,15,5,40,20,8,20])

In [136]:
print('Time for looking apartments:\n', np.dot(looking_time, A[:,4]))

Time for looking apartments:
 1348


## Task 2

In [137]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

## 1.7.8

In [139]:
a = 2*v+(-3)*w
print('linear combination of v and w:\n', a)

linear combination of v and w:
 [-3 14  3  4  2]


## 1.7.9

In [141]:
print('u and new vector ortogonality:\n', np.dot(u,a))

u and new vector ortogonality:
 0


## 1.7.10

In [149]:
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)
print('u_norm, v_norm,w_norm respectively:\n', u_norm[2], v_norm[3],w_norm[0])

u_norm, v_norm,w_norm respectively:
 0.2886751345948129 0.6666666666666666 0.21320071635561041


# 1.10. Matrices

In [ ]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

## 1.10.1

In [369]:
Inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income])

In [181]:
Inc = Inc.T

In [182]:
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [185]:
Cons = np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption])

In [186]:
Cons = Cons.T

In [187]:
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [188]:
Disposable_Inc = Inc*0.87

In [189]:
Disposable_Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [190]:
P = Disposable_Inc-Cons

In [191]:
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

## 1.15

In [192]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [193]:
A*x

array([[ 5, -2,  9,  4, 10],
       [-2, 16, 15, -4,  5]])

In [194]:
x*A

array([[ 5, -2,  9,  4, 10],
       [-2, 16, 15, -4,  5]])

In [195]:
print(A@x)

[26 30]


'Namme aaa gggdd mak'

Namme Aaa gggdd mak


'Abra Ka dabra'

['Abra', 'Ka', 'dabra']


'Abra Ka dabra'

''

'First A Of In'